//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USO.Infrastructure.Xinyong.WebServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Xinyong.WebServices.UpdateCustomerSoap")]
    public interface UpdateCustomerSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Kunnr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        USO.Infrastructure.Xinyong.WebServices.UpdateResponse Update(USO.Infrastructure.Xinyong.WebServices.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<USO.Infrastructure.Xinyong.WebServices.UpdateResponse> UpdateAsync(USO.Infrastructure.Xinyong.WebServices.UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public USO.Infrastructure.Xinyong.WebServices.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(USO.Infrastructure.Xinyong.WebServices.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Kunnr;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(string Kunnr) {
            this.Kunnr = Kunnr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public USO.Infrastructure.Xinyong.WebServices.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(USO.Infrastructure.Xinyong.WebServices.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(string UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UpdateCustomerSoapChannel : USO.Infrastructure.Xinyong.WebServices.UpdateCustomerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateCustomerSoapClient : System.ServiceModel.ClientBase<USO.Infrastructure.Xinyong.WebServices.UpdateCustomerSoap>, USO.Infrastructure.Xinyong.WebServices.UpdateCustomerSoap {
        
        public UpdateCustomerSoapClient() {
        }
        
        public UpdateCustomerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateCustomerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateCustomerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateCustomerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        USO.Infrastructure.Xinyong.WebServices.UpdateResponse USO.Infrastructure.Xinyong.WebServices.UpdateCustomerSoap.Update(USO.Infrastructure.Xinyong.WebServices.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public string Update(string Kunnr) {
            USO.Infrastructure.Xinyong.WebServices.UpdateRequest inValue = new USO.Infrastructure.Xinyong.WebServices.UpdateRequest();
            inValue.Body = new USO.Infrastructure.Xinyong.WebServices.UpdateRequestBody();
            inValue.Body.Kunnr = Kunnr;
            USO.Infrastructure.Xinyong.WebServices.UpdateResponse retVal = ((USO.Infrastructure.Xinyong.WebServices.UpdateCustomerSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<USO.Infrastructure.Xinyong.WebServices.UpdateResponse> USO.Infrastructure.Xinyong.WebServices.UpdateCustomerSoap.UpdateAsync(USO.Infrastructure.Xinyong.WebServices.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<USO.Infrastructure.Xinyong.WebServices.UpdateResponse> UpdateAsync(string Kunnr) {
            USO.Infrastructure.Xinyong.WebServices.UpdateRequest inValue = new USO.Infrastructure.Xinyong.WebServices.UpdateRequest();
            inValue.Body = new USO.Infrastructure.Xinyong.WebServices.UpdateRequestBody();
            inValue.Body.Kunnr = Kunnr;
            return ((USO.Infrastructure.Xinyong.WebServices.UpdateCustomerSoap)(this)).UpdateAsync(inValue);
        }
    }
}
