//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USO.Infrastructure.R3PriceWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="R3PriceWebService.ZWS_ZINT_SD0012")]
    public interface ZWS_ZINT_SD0012 {
        
        // CODEGEN: 操作 ZintSd0012 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_ZINT_SD0012:ZintSd0012Reques" +
            "t", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        USO.Infrastructure.R3PriceWebService.ZintSd0012Response1 ZintSd0012(USO.Infrastructure.R3PriceWebService.ZintSd0012Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_ZINT_SD0012:ZintSd0012Reques" +
            "t", ReplyAction="*")]
        System.Threading.Tasks.Task<USO.Infrastructure.R3PriceWebService.ZintSd0012Response1> ZintSd0012Async(USO.Infrastructure.R3PriceWebService.ZintSd0012Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZintSd0012 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Zsa004 inA004Field;
        
        private Zsa005 inA005Field;
        
        private Zsa508 inA508Field;
        
        private Zsa710 inA710Field;
        
        private Zsa760 inA760Field;
        
        private Zsa763 inA763Field;
        
        private Zsa764 inA764Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Zsa004 InA004 {
            get {
                return this.inA004Field;
            }
            set {
                this.inA004Field = value;
                this.RaisePropertyChanged("InA004");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Zsa005 InA005 {
            get {
                return this.inA005Field;
            }
            set {
                this.inA005Field = value;
                this.RaisePropertyChanged("InA005");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Zsa508 InA508 {
            get {
                return this.inA508Field;
            }
            set {
                this.inA508Field = value;
                this.RaisePropertyChanged("InA508");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Zsa710 InA710 {
            get {
                return this.inA710Field;
            }
            set {
                this.inA710Field = value;
                this.RaisePropertyChanged("InA710");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public Zsa760 InA760 {
            get {
                return this.inA760Field;
            }
            set {
                this.inA760Field = value;
                this.RaisePropertyChanged("InA760");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public Zsa763 InA763 {
            get {
                return this.inA763Field;
            }
            set {
                this.inA763Field = value;
                this.RaisePropertyChanged("InA763");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public Zsa764 InA764 {
            get {
                return this.inA764Field;
            }
            set {
                this.inA764Field = value;
                this.RaisePropertyChanged("InA764");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zsa004 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kschlField;
        
        private string vkorgField;
        
        private string vtwegField;
        
        private string matnrField;
        
        private decimal kbetrField;
        
        private string konwaField;
        
        private decimal kpeinField;
        
        private string databField;
        
        private string datbiField;
        
        private decimal mxwrtField;
        
        private decimal gkwrtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Kschl {
            get {
                return this.kschlField;
            }
            set {
                this.kschlField = value;
                this.RaisePropertyChanged("Kschl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Vkorg {
            get {
                return this.vkorgField;
            }
            set {
                this.vkorgField = value;
                this.RaisePropertyChanged("Vkorg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Vtweg {
            get {
                return this.vtwegField;
            }
            set {
                this.vtwegField = value;
                this.RaisePropertyChanged("Vtweg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
                this.RaisePropertyChanged("Matnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal Kbetr {
            get {
                return this.kbetrField;
            }
            set {
                this.kbetrField = value;
                this.RaisePropertyChanged("Kbetr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Konwa {
            get {
                return this.konwaField;
            }
            set {
                this.konwaField = value;
                this.RaisePropertyChanged("Konwa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal Kpein {
            get {
                return this.kpeinField;
            }
            set {
                this.kpeinField = value;
                this.RaisePropertyChanged("Kpein");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Datab {
            get {
                return this.databField;
            }
            set {
                this.databField = value;
                this.RaisePropertyChanged("Datab");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Datbi {
            get {
                return this.datbiField;
            }
            set {
                this.datbiField = value;
                this.RaisePropertyChanged("Datbi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal Mxwrt {
            get {
                return this.mxwrtField;
            }
            set {
                this.mxwrtField = value;
                this.RaisePropertyChanged("Mxwrt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal Gkwrt {
            get {
                return this.gkwrtField;
            }
            set {
                this.gkwrtField = value;
                this.RaisePropertyChanged("Gkwrt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zsa764 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kschlField;
        
        private string vkorgField;
        
        private string vtwegField;
        
        private string vkburField;
        
        private string vkgrpField;
        
        private string matnrField;
        
        private decimal kbetrField;
        
        private string konwaField;
        
        private decimal kpeinField;
        
        private string databField;
        
        private string datbiField;
        
        private decimal mxwrtField;
        
        private decimal gkwrtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Kschl {
            get {
                return this.kschlField;
            }
            set {
                this.kschlField = value;
                this.RaisePropertyChanged("Kschl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Vkorg {
            get {
                return this.vkorgField;
            }
            set {
                this.vkorgField = value;
                this.RaisePropertyChanged("Vkorg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Vtweg {
            get {
                return this.vtwegField;
            }
            set {
                this.vtwegField = value;
                this.RaisePropertyChanged("Vtweg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Vkbur {
            get {
                return this.vkburField;
            }
            set {
                this.vkburField = value;
                this.RaisePropertyChanged("Vkbur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Vkgrp {
            get {
                return this.vkgrpField;
            }
            set {
                this.vkgrpField = value;
                this.RaisePropertyChanged("Vkgrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
                this.RaisePropertyChanged("Matnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal Kbetr {
            get {
                return this.kbetrField;
            }
            set {
                this.kbetrField = value;
                this.RaisePropertyChanged("Kbetr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Konwa {
            get {
                return this.konwaField;
            }
            set {
                this.konwaField = value;
                this.RaisePropertyChanged("Konwa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal Kpein {
            get {
                return this.kpeinField;
            }
            set {
                this.kpeinField = value;
                this.RaisePropertyChanged("Kpein");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Datab {
            get {
                return this.databField;
            }
            set {
                this.databField = value;
                this.RaisePropertyChanged("Datab");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Datbi {
            get {
                return this.datbiField;
            }
            set {
                this.datbiField = value;
                this.RaisePropertyChanged("Datbi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal Mxwrt {
            get {
                return this.mxwrtField;
            }
            set {
                this.mxwrtField = value;
                this.RaisePropertyChanged("Mxwrt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal Gkwrt {
            get {
                return this.gkwrtField;
            }
            set {
                this.gkwrtField = value;
                this.RaisePropertyChanged("Gkwrt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zsa763 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kschlField;
        
        private string vkorgField;
        
        private string vtwegField;
        
        private string werksField;
        
        private string matnrField;
        
        private decimal kbetrField;
        
        private string konwaField;
        
        private decimal kpeinField;
        
        private string databField;
        
        private string datbiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Kschl {
            get {
                return this.kschlField;
            }
            set {
                this.kschlField = value;
                this.RaisePropertyChanged("Kschl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Vkorg {
            get {
                return this.vkorgField;
            }
            set {
                this.vkorgField = value;
                this.RaisePropertyChanged("Vkorg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Vtweg {
            get {
                return this.vtwegField;
            }
            set {
                this.vtwegField = value;
                this.RaisePropertyChanged("Vtweg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Werks {
            get {
                return this.werksField;
            }
            set {
                this.werksField = value;
                this.RaisePropertyChanged("Werks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
                this.RaisePropertyChanged("Matnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal Kbetr {
            get {
                return this.kbetrField;
            }
            set {
                this.kbetrField = value;
                this.RaisePropertyChanged("Kbetr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Konwa {
            get {
                return this.konwaField;
            }
            set {
                this.konwaField = value;
                this.RaisePropertyChanged("Konwa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal Kpein {
            get {
                return this.kpeinField;
            }
            set {
                this.kpeinField = value;
                this.RaisePropertyChanged("Kpein");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Datab {
            get {
                return this.databField;
            }
            set {
                this.databField = value;
                this.RaisePropertyChanged("Datab");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Datbi {
            get {
                return this.datbiField;
            }
            set {
                this.datbiField = value;
                this.RaisePropertyChanged("Datbi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zsa760 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kschlField;
        
        private string vkorgField;
        
        private string vtwegField;
        
        private string kunnrField;
        
        private string zzihrezField;
        
        private string matnrField;
        
        private decimal kbetrField;
        
        private string konwaField;
        
        private decimal kpeinField;
        
        private string databField;
        
        private string datbiField;
        
        private decimal mxwrtField;
        
        private decimal gkwrtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Kschl {
            get {
                return this.kschlField;
            }
            set {
                this.kschlField = value;
                this.RaisePropertyChanged("Kschl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Vkorg {
            get {
                return this.vkorgField;
            }
            set {
                this.vkorgField = value;
                this.RaisePropertyChanged("Vkorg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Vtweg {
            get {
                return this.vtwegField;
            }
            set {
                this.vtwegField = value;
                this.RaisePropertyChanged("Vtweg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Kunnr {
            get {
                return this.kunnrField;
            }
            set {
                this.kunnrField = value;
                this.RaisePropertyChanged("Kunnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Zzihrez {
            get {
                return this.zzihrezField;
            }
            set {
                this.zzihrezField = value;
                this.RaisePropertyChanged("Zzihrez");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
                this.RaisePropertyChanged("Matnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal Kbetr {
            get {
                return this.kbetrField;
            }
            set {
                this.kbetrField = value;
                this.RaisePropertyChanged("Kbetr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Konwa {
            get {
                return this.konwaField;
            }
            set {
                this.konwaField = value;
                this.RaisePropertyChanged("Konwa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal Kpein {
            get {
                return this.kpeinField;
            }
            set {
                this.kpeinField = value;
                this.RaisePropertyChanged("Kpein");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Datab {
            get {
                return this.databField;
            }
            set {
                this.databField = value;
                this.RaisePropertyChanged("Datab");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Datbi {
            get {
                return this.datbiField;
            }
            set {
                this.datbiField = value;
                this.RaisePropertyChanged("Datbi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal Mxwrt {
            get {
                return this.mxwrtField;
            }
            set {
                this.mxwrtField = value;
                this.RaisePropertyChanged("Mxwrt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal Gkwrt {
            get {
                return this.gkwrtField;
            }
            set {
                this.gkwrtField = value;
                this.RaisePropertyChanged("Gkwrt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zsa710 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kschlField;
        
        private string vkorgField;
        
        private string vtwegField;
        
        private string vkburField;
        
        private string matnrField;
        
        private decimal kbetrField;
        
        private string konwaField;
        
        private decimal kpeinField;
        
        private string databField;
        
        private string datbiField;
        
        private decimal mxwrtField;
        
        private decimal gkwrtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Kschl {
            get {
                return this.kschlField;
            }
            set {
                this.kschlField = value;
                this.RaisePropertyChanged("Kschl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Vkorg {
            get {
                return this.vkorgField;
            }
            set {
                this.vkorgField = value;
                this.RaisePropertyChanged("Vkorg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Vtweg {
            get {
                return this.vtwegField;
            }
            set {
                this.vtwegField = value;
                this.RaisePropertyChanged("Vtweg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Vkbur {
            get {
                return this.vkburField;
            }
            set {
                this.vkburField = value;
                this.RaisePropertyChanged("Vkbur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
                this.RaisePropertyChanged("Matnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal Kbetr {
            get {
                return this.kbetrField;
            }
            set {
                this.kbetrField = value;
                this.RaisePropertyChanged("Kbetr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Konwa {
            get {
                return this.konwaField;
            }
            set {
                this.konwaField = value;
                this.RaisePropertyChanged("Konwa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal Kpein {
            get {
                return this.kpeinField;
            }
            set {
                this.kpeinField = value;
                this.RaisePropertyChanged("Kpein");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Datab {
            get {
                return this.databField;
            }
            set {
                this.databField = value;
                this.RaisePropertyChanged("Datab");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Datbi {
            get {
                return this.datbiField;
            }
            set {
                this.datbiField = value;
                this.RaisePropertyChanged("Datbi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal Mxwrt {
            get {
                return this.mxwrtField;
            }
            set {
                this.mxwrtField = value;
                this.RaisePropertyChanged("Mxwrt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal Gkwrt {
            get {
                return this.gkwrtField;
            }
            set {
                this.gkwrtField = value;
                this.RaisePropertyChanged("Gkwrt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zsa508 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kschlField;
        
        private string vkorgField;
        
        private string vtwegField;
        
        private string kunnrField;
        
        private string matnrField;
        
        private string vkburField;
        
        private decimal kbetrField;
        
        private string konwaField;
        
        private decimal kpeinField;
        
        private string databField;
        
        private string datbiField;
        
        private decimal mxwrtField;
        
        private decimal gkwrtField;
        
        private string kmeinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Kschl {
            get {
                return this.kschlField;
            }
            set {
                this.kschlField = value;
                this.RaisePropertyChanged("Kschl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Vkorg {
            get {
                return this.vkorgField;
            }
            set {
                this.vkorgField = value;
                this.RaisePropertyChanged("Vkorg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Vtweg {
            get {
                return this.vtwegField;
            }
            set {
                this.vtwegField = value;
                this.RaisePropertyChanged("Vtweg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Kunnr {
            get {
                return this.kunnrField;
            }
            set {
                this.kunnrField = value;
                this.RaisePropertyChanged("Kunnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
                this.RaisePropertyChanged("Matnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Vkbur {
            get {
                return this.vkburField;
            }
            set {
                this.vkburField = value;
                this.RaisePropertyChanged("Vkbur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal Kbetr {
            get {
                return this.kbetrField;
            }
            set {
                this.kbetrField = value;
                this.RaisePropertyChanged("Kbetr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Konwa {
            get {
                return this.konwaField;
            }
            set {
                this.konwaField = value;
                this.RaisePropertyChanged("Konwa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal Kpein {
            get {
                return this.kpeinField;
            }
            set {
                this.kpeinField = value;
                this.RaisePropertyChanged("Kpein");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Datab {
            get {
                return this.databField;
            }
            set {
                this.databField = value;
                this.RaisePropertyChanged("Datab");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Datbi {
            get {
                return this.datbiField;
            }
            set {
                this.datbiField = value;
                this.RaisePropertyChanged("Datbi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal Mxwrt {
            get {
                return this.mxwrtField;
            }
            set {
                this.mxwrtField = value;
                this.RaisePropertyChanged("Mxwrt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal Gkwrt {
            get {
                return this.gkwrtField;
            }
            set {
                this.gkwrtField = value;
                this.RaisePropertyChanged("Gkwrt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Kmein {
            get {
                return this.kmeinField;
            }
            set {
                this.kmeinField = value;
                this.RaisePropertyChanged("Kmein");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zsa005 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kschlField;
        
        private string vkorgField;
        
        private string vtwegField;
        
        private string kunnrField;
        
        private string matnrField;
        
        private decimal kbetrField;
        
        private string konwaField;
        
        private decimal kpeinField;
        
        private string databField;
        
        private string datbiField;
        
        private decimal mxwrtField;
        
        private decimal gkwrtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Kschl {
            get {
                return this.kschlField;
            }
            set {
                this.kschlField = value;
                this.RaisePropertyChanged("Kschl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Vkorg {
            get {
                return this.vkorgField;
            }
            set {
                this.vkorgField = value;
                this.RaisePropertyChanged("Vkorg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Vtweg {
            get {
                return this.vtwegField;
            }
            set {
                this.vtwegField = value;
                this.RaisePropertyChanged("Vtweg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Kunnr {
            get {
                return this.kunnrField;
            }
            set {
                this.kunnrField = value;
                this.RaisePropertyChanged("Kunnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
                this.RaisePropertyChanged("Matnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal Kbetr {
            get {
                return this.kbetrField;
            }
            set {
                this.kbetrField = value;
                this.RaisePropertyChanged("Kbetr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Konwa {
            get {
                return this.konwaField;
            }
            set {
                this.konwaField = value;
                this.RaisePropertyChanged("Konwa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal Kpein {
            get {
                return this.kpeinField;
            }
            set {
                this.kpeinField = value;
                this.RaisePropertyChanged("Kpein");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Datab {
            get {
                return this.databField;
            }
            set {
                this.databField = value;
                this.RaisePropertyChanged("Datab");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Datbi {
            get {
                return this.datbiField;
            }
            set {
                this.datbiField = value;
                this.RaisePropertyChanged("Datbi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal Mxwrt {
            get {
                return this.mxwrtField;
            }
            set {
                this.mxwrtField = value;
                this.RaisePropertyChanged("Mxwrt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal Gkwrt {
            get {
                return this.gkwrtField;
            }
            set {
                this.gkwrtField = value;
                this.RaisePropertyChanged("Gkwrt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZintSd0012Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string retidField;
        
        private string retmsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Retid {
            get {
                return this.retidField;
            }
            set {
                this.retidField = value;
                this.RaisePropertyChanged("Retid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Retmsg {
            get {
                return this.retmsgField;
            }
            set {
                this.retmsgField = value;
                this.RaisePropertyChanged("Retmsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZintSd0012Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public USO.Infrastructure.R3PriceWebService.ZintSd0012 ZintSd0012;
        
        public ZintSd0012Request() {
        }
        
        public ZintSd0012Request(USO.Infrastructure.R3PriceWebService.ZintSd0012 ZintSd0012) {
            this.ZintSd0012 = ZintSd0012;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZintSd0012Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public USO.Infrastructure.R3PriceWebService.ZintSd0012Response ZintSd0012Response;
        
        public ZintSd0012Response1() {
        }
        
        public ZintSd0012Response1(USO.Infrastructure.R3PriceWebService.ZintSd0012Response ZintSd0012Response) {
            this.ZintSd0012Response = ZintSd0012Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_ZINT_SD0012Channel : USO.Infrastructure.R3PriceWebService.ZWS_ZINT_SD0012, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_ZINT_SD0012Client : System.ServiceModel.ClientBase<USO.Infrastructure.R3PriceWebService.ZWS_ZINT_SD0012>, USO.Infrastructure.R3PriceWebService.ZWS_ZINT_SD0012 {
        
        public ZWS_ZINT_SD0012Client() {
        }
        
        public ZWS_ZINT_SD0012Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_ZINT_SD0012Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZINT_SD0012Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZINT_SD0012Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        USO.Infrastructure.R3PriceWebService.ZintSd0012Response1 USO.Infrastructure.R3PriceWebService.ZWS_ZINT_SD0012.ZintSd0012(USO.Infrastructure.R3PriceWebService.ZintSd0012Request request) {
            return base.Channel.ZintSd0012(request);
        }
        
        public USO.Infrastructure.R3PriceWebService.ZintSd0012Response ZintSd0012(USO.Infrastructure.R3PriceWebService.ZintSd0012 ZintSd00121) {
            USO.Infrastructure.R3PriceWebService.ZintSd0012Request inValue = new USO.Infrastructure.R3PriceWebService.ZintSd0012Request();
            inValue.ZintSd0012 = ZintSd00121;
            USO.Infrastructure.R3PriceWebService.ZintSd0012Response1 retVal = ((USO.Infrastructure.R3PriceWebService.ZWS_ZINT_SD0012)(this)).ZintSd0012(inValue);
            return retVal.ZintSd0012Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<USO.Infrastructure.R3PriceWebService.ZintSd0012Response1> USO.Infrastructure.R3PriceWebService.ZWS_ZINT_SD0012.ZintSd0012Async(USO.Infrastructure.R3PriceWebService.ZintSd0012Request request) {
            return base.Channel.ZintSd0012Async(request);
        }
        
        public System.Threading.Tasks.Task<USO.Infrastructure.R3PriceWebService.ZintSd0012Response1> ZintSd0012Async(USO.Infrastructure.R3PriceWebService.ZintSd0012 ZintSd0012) {
            USO.Infrastructure.R3PriceWebService.ZintSd0012Request inValue = new USO.Infrastructure.R3PriceWebService.ZintSd0012Request();
            inValue.ZintSd0012 = ZintSd0012;
            return ((USO.Infrastructure.R3PriceWebService.ZWS_ZINT_SD0012)(this)).ZintSd0012Async(inValue);
        }
    }
}
