//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USO.Infrastructure.DeleteR3OrderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="DeleteR3OrderService.ZWS_ZINT_SD0026")]
    public interface ZWS_ZINT_SD0026 {
        
        // CODEGEN: 操作 ZintSd0026 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_ZINT_SD0026:ZintSd0026Reques" +
            "t", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        USO.Infrastructure.DeleteR3OrderService.ZintSd0026Response1 ZintSd0026(USO.Infrastructure.DeleteR3OrderService.ZintSd0026Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_ZINT_SD0026:ZintSd0026Reques" +
            "t", ReplyAction="*")]
        System.Threading.Tasks.Task<USO.Infrastructure.DeleteR3OrderService.ZintSd0026Response1> ZintSd0026Async(USO.Infrastructure.DeleteR3OrderService.ZintSd0026Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZintSd0026 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vbelnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Vbeln {
            get {
                return this.vbelnField;
            }
            set {
                this.vbelnField = value;
                this.RaisePropertyChanged("Vbeln");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZintSd0026Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string retcodeField;
        
        private string retmsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Retcode {
            get {
                return this.retcodeField;
            }
            set {
                this.retcodeField = value;
                this.RaisePropertyChanged("Retcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Retmsg {
            get {
                return this.retmsgField;
            }
            set {
                this.retmsgField = value;
                this.RaisePropertyChanged("Retmsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZintSd0026Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public USO.Infrastructure.DeleteR3OrderService.ZintSd0026 ZintSd0026;
        
        public ZintSd0026Request() {
        }
        
        public ZintSd0026Request(USO.Infrastructure.DeleteR3OrderService.ZintSd0026 ZintSd0026) {
            this.ZintSd0026 = ZintSd0026;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZintSd0026Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public USO.Infrastructure.DeleteR3OrderService.ZintSd0026Response ZintSd0026Response;
        
        public ZintSd0026Response1() {
        }
        
        public ZintSd0026Response1(USO.Infrastructure.DeleteR3OrderService.ZintSd0026Response ZintSd0026Response) {
            this.ZintSd0026Response = ZintSd0026Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_ZINT_SD0026Channel : USO.Infrastructure.DeleteR3OrderService.ZWS_ZINT_SD0026, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_ZINT_SD0026Client : System.ServiceModel.ClientBase<USO.Infrastructure.DeleteR3OrderService.ZWS_ZINT_SD0026>, USO.Infrastructure.DeleteR3OrderService.ZWS_ZINT_SD0026 {
        
        public ZWS_ZINT_SD0026Client() {
        }
        
        public ZWS_ZINT_SD0026Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_ZINT_SD0026Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZINT_SD0026Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZINT_SD0026Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        USO.Infrastructure.DeleteR3OrderService.ZintSd0026Response1 USO.Infrastructure.DeleteR3OrderService.ZWS_ZINT_SD0026.ZintSd0026(USO.Infrastructure.DeleteR3OrderService.ZintSd0026Request request) {
            return base.Channel.ZintSd0026(request);
        }
        
        public USO.Infrastructure.DeleteR3OrderService.ZintSd0026Response ZintSd0026(USO.Infrastructure.DeleteR3OrderService.ZintSd0026 ZintSd00261) {
            USO.Infrastructure.DeleteR3OrderService.ZintSd0026Request inValue = new USO.Infrastructure.DeleteR3OrderService.ZintSd0026Request();
            inValue.ZintSd0026 = ZintSd00261;
            USO.Infrastructure.DeleteR3OrderService.ZintSd0026Response1 retVal = ((USO.Infrastructure.DeleteR3OrderService.ZWS_ZINT_SD0026)(this)).ZintSd0026(inValue);
            return retVal.ZintSd0026Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<USO.Infrastructure.DeleteR3OrderService.ZintSd0026Response1> USO.Infrastructure.DeleteR3OrderService.ZWS_ZINT_SD0026.ZintSd0026Async(USO.Infrastructure.DeleteR3OrderService.ZintSd0026Request request) {
            return base.Channel.ZintSd0026Async(request);
        }
        
        public System.Threading.Tasks.Task<USO.Infrastructure.DeleteR3OrderService.ZintSd0026Response1> ZintSd0026Async(USO.Infrastructure.DeleteR3OrderService.ZintSd0026 ZintSd0026) {
            USO.Infrastructure.DeleteR3OrderService.ZintSd0026Request inValue = new USO.Infrastructure.DeleteR3OrderService.ZintSd0026Request();
            inValue.ZintSd0026 = ZintSd0026;
            return ((USO.Infrastructure.DeleteR3OrderService.ZWS_ZINT_SD0026)(this)).ZintSd0026Async(inValue);
        }
    }
}
