//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USO.Infrastructure.R3CustomerSalesAreaWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="R3CustomerSalesAreaWebService.ZWS_ZRFC_CREATE_SA")]
    public interface ZWS_ZRFC_CREATE_SA {
        
        // CODEGEN: 操作 ZrfcCreateSa 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_ZRFC_CREATE_SA:ZrfcCreateSaR" +
            "equest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSaResponse1 ZrfcCreateSa(USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_ZRFC_CREATE_SA:ZrfcCreateSaR" +
            "equest", ReplyAction="*")]
        System.Threading.Tasks.Task<USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSaResponse1> ZrfcCreateSaAsync(USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZrfcCreateSa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Zcustomerinfo[] tCustomerinfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zcustomerinfo[] TCustomerinfo {
            get {
                return this.tCustomerinfoField;
            }
            set {
                this.tCustomerinfoField = value;
                this.RaisePropertyChanged("TCustomerinfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zcustomerinfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kunnrField;
        
        private string ktokdField;
        
        private string anredField;
        
        private string name1Field;
        
        private string sortlField;
        
        private string streetField;
        
        private string suppl1Field;
        
        private string pstlzField;
        
        private string cityField;
        
        private string countryField;
        
        private string regionField;
        
        private string sprasField;
        
        private string lzoneField;
        
        private string telf1Field;
        
        private string fax1Field;
        
        private string telbxField;
        
        private string stcegField;
        
        private string akontField;
        
        private string zuawaField;
        
        private string begruField;
        
        private string knrzeField;
        
        private string fdgrvField;
        
        private string bzirkField;
        
        private string vkburField;
        
        private string vkgrpField;
        
        private string kdgrpField;
        
        private string waersField;
        
        private string kondaField;
        
        private string kalksField;
        
        private string versgField;
        
        private string vsbedField;
        
        private string vwerkField;
        
        private string ktgrdField;
        
        private string taxkdField;
        
        private string ktonrField;
        
        private string bukrsField;
        
        private string vkorgField;
        
        private string vtwegField;
        
        private string spartField;
        
        private string inco1Field;
        
        private string inco2Field;
        
        private string ztermField;
        
        private string lifnrField;
        
        private string name2Field;
        
        private string brschField;
        
        private string kuklaField;
        
        private string podkzField;
        
        private string klabcField;
        
        private string suppl2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Kunnr {
            get {
                return this.kunnrField;
            }
            set {
                this.kunnrField = value;
                this.RaisePropertyChanged("Kunnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Ktokd {
            get {
                return this.ktokdField;
            }
            set {
                this.ktokdField = value;
                this.RaisePropertyChanged("Ktokd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Anred {
            get {
                return this.anredField;
            }
            set {
                this.anredField = value;
                this.RaisePropertyChanged("Anred");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Name1 {
            get {
                return this.name1Field;
            }
            set {
                this.name1Field = value;
                this.RaisePropertyChanged("Name1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Sortl {
            get {
                return this.sortlField;
            }
            set {
                this.sortlField = value;
                this.RaisePropertyChanged("Sortl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Suppl1 {
            get {
                return this.suppl1Field;
            }
            set {
                this.suppl1Field = value;
                this.RaisePropertyChanged("Suppl1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Pstlz {
            get {
                return this.pstlzField;
            }
            set {
                this.pstlzField = value;
                this.RaisePropertyChanged("Pstlz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Spras {
            get {
                return this.sprasField;
            }
            set {
                this.sprasField = value;
                this.RaisePropertyChanged("Spras");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Lzone {
            get {
                return this.lzoneField;
            }
            set {
                this.lzoneField = value;
                this.RaisePropertyChanged("Lzone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Telf1 {
            get {
                return this.telf1Field;
            }
            set {
                this.telf1Field = value;
                this.RaisePropertyChanged("Telf1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Fax1 {
            get {
                return this.fax1Field;
            }
            set {
                this.fax1Field = value;
                this.RaisePropertyChanged("Fax1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Telbx {
            get {
                return this.telbxField;
            }
            set {
                this.telbxField = value;
                this.RaisePropertyChanged("Telbx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Stceg {
            get {
                return this.stcegField;
            }
            set {
                this.stcegField = value;
                this.RaisePropertyChanged("Stceg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Akont {
            get {
                return this.akontField;
            }
            set {
                this.akontField = value;
                this.RaisePropertyChanged("Akont");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Zuawa {
            get {
                return this.zuawaField;
            }
            set {
                this.zuawaField = value;
                this.RaisePropertyChanged("Zuawa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Begru {
            get {
                return this.begruField;
            }
            set {
                this.begruField = value;
                this.RaisePropertyChanged("Begru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string Knrze {
            get {
                return this.knrzeField;
            }
            set {
                this.knrzeField = value;
                this.RaisePropertyChanged("Knrze");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string Fdgrv {
            get {
                return this.fdgrvField;
            }
            set {
                this.fdgrvField = value;
                this.RaisePropertyChanged("Fdgrv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string Bzirk {
            get {
                return this.bzirkField;
            }
            set {
                this.bzirkField = value;
                this.RaisePropertyChanged("Bzirk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string Vkbur {
            get {
                return this.vkburField;
            }
            set {
                this.vkburField = value;
                this.RaisePropertyChanged("Vkbur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string Vkgrp {
            get {
                return this.vkgrpField;
            }
            set {
                this.vkgrpField = value;
                this.RaisePropertyChanged("Vkgrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string Kdgrp {
            get {
                return this.kdgrpField;
            }
            set {
                this.kdgrpField = value;
                this.RaisePropertyChanged("Kdgrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string Waers {
            get {
                return this.waersField;
            }
            set {
                this.waersField = value;
                this.RaisePropertyChanged("Waers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string Konda {
            get {
                return this.kondaField;
            }
            set {
                this.kondaField = value;
                this.RaisePropertyChanged("Konda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string Kalks {
            get {
                return this.kalksField;
            }
            set {
                this.kalksField = value;
                this.RaisePropertyChanged("Kalks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string Versg {
            get {
                return this.versgField;
            }
            set {
                this.versgField = value;
                this.RaisePropertyChanged("Versg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string Vsbed {
            get {
                return this.vsbedField;
            }
            set {
                this.vsbedField = value;
                this.RaisePropertyChanged("Vsbed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string Vwerk {
            get {
                return this.vwerkField;
            }
            set {
                this.vwerkField = value;
                this.RaisePropertyChanged("Vwerk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string Ktgrd {
            get {
                return this.ktgrdField;
            }
            set {
                this.ktgrdField = value;
                this.RaisePropertyChanged("Ktgrd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string Taxkd {
            get {
                return this.taxkdField;
            }
            set {
                this.taxkdField = value;
                this.RaisePropertyChanged("Taxkd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string Ktonr {
            get {
                return this.ktonrField;
            }
            set {
                this.ktonrField = value;
                this.RaisePropertyChanged("Ktonr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string Bukrs {
            get {
                return this.bukrsField;
            }
            set {
                this.bukrsField = value;
                this.RaisePropertyChanged("Bukrs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string Vkorg {
            get {
                return this.vkorgField;
            }
            set {
                this.vkorgField = value;
                this.RaisePropertyChanged("Vkorg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string Vtweg {
            get {
                return this.vtwegField;
            }
            set {
                this.vtwegField = value;
                this.RaisePropertyChanged("Vtweg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string Spart {
            get {
                return this.spartField;
            }
            set {
                this.spartField = value;
                this.RaisePropertyChanged("Spart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string Inco1 {
            get {
                return this.inco1Field;
            }
            set {
                this.inco1Field = value;
                this.RaisePropertyChanged("Inco1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string Inco2 {
            get {
                return this.inco2Field;
            }
            set {
                this.inco2Field = value;
                this.RaisePropertyChanged("Inco2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string Zterm {
            get {
                return this.ztermField;
            }
            set {
                this.ztermField = value;
                this.RaisePropertyChanged("Zterm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string Lifnr {
            get {
                return this.lifnrField;
            }
            set {
                this.lifnrField = value;
                this.RaisePropertyChanged("Lifnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string Name2 {
            get {
                return this.name2Field;
            }
            set {
                this.name2Field = value;
                this.RaisePropertyChanged("Name2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string Brsch {
            get {
                return this.brschField;
            }
            set {
                this.brschField = value;
                this.RaisePropertyChanged("Brsch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string Kukla {
            get {
                return this.kuklaField;
            }
            set {
                this.kuklaField = value;
                this.RaisePropertyChanged("Kukla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string Podkz {
            get {
                return this.podkzField;
            }
            set {
                this.podkzField = value;
                this.RaisePropertyChanged("Podkz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string Klabc {
            get {
                return this.klabcField;
            }
            set {
                this.klabcField = value;
                this.RaisePropertyChanged("Klabc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string Suppl2 {
            get {
                return this.suppl2Field;
            }
            set {
                this.suppl2Field = value;
                this.RaisePropertyChanged("Suppl2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapireturn1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string idField;
        
        private string numberField;
        
        private string messageField;
        
        private string logNoField;
        
        private string logMsgNoField;
        
        private string messageV1Field;
        
        private string messageV2Field;
        
        private string messageV3Field;
        
        private string messageV4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LogNo {
            get {
                return this.logNoField;
            }
            set {
                this.logNoField = value;
                this.RaisePropertyChanged("LogNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LogMsgNo {
            get {
                return this.logMsgNoField;
            }
            set {
                this.logMsgNoField = value;
                this.RaisePropertyChanged("LogMsgNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MessageV1 {
            get {
                return this.messageV1Field;
            }
            set {
                this.messageV1Field = value;
                this.RaisePropertyChanged("MessageV1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MessageV2 {
            get {
                return this.messageV2Field;
            }
            set {
                this.messageV2Field = value;
                this.RaisePropertyChanged("MessageV2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MessageV3 {
            get {
                return this.messageV3Field;
            }
            set {
                this.messageV3Field = value;
                this.RaisePropertyChanged("MessageV3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MessageV4 {
            get {
                return this.messageV4Field;
            }
            set {
                this.messageV4Field = value;
                this.RaisePropertyChanged("MessageV4");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZrfcCreateSaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errmessageField;
        
        private Bapireturn1 returnField;
        
        private Zcustomerinfo[] tCustomerinfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Errmessage {
            get {
                return this.errmessageField;
            }
            set {
                this.errmessageField = value;
                this.RaisePropertyChanged("Errmessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Bapireturn1 Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zcustomerinfo[] TCustomerinfo {
            get {
                return this.tCustomerinfoField;
            }
            set {
                this.tCustomerinfoField = value;
                this.RaisePropertyChanged("TCustomerinfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZrfcCreateSaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSa ZrfcCreateSa;
        
        public ZrfcCreateSaRequest() {
        }
        
        public ZrfcCreateSaRequest(USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSa ZrfcCreateSa) {
            this.ZrfcCreateSa = ZrfcCreateSa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZrfcCreateSaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSaResponse ZrfcCreateSaResponse;
        
        public ZrfcCreateSaResponse1() {
        }
        
        public ZrfcCreateSaResponse1(USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSaResponse ZrfcCreateSaResponse) {
            this.ZrfcCreateSaResponse = ZrfcCreateSaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_ZRFC_CREATE_SAChannel : USO.Infrastructure.R3CustomerSalesAreaWebService.ZWS_ZRFC_CREATE_SA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_ZRFC_CREATE_SAClient : System.ServiceModel.ClientBase<USO.Infrastructure.R3CustomerSalesAreaWebService.ZWS_ZRFC_CREATE_SA>, USO.Infrastructure.R3CustomerSalesAreaWebService.ZWS_ZRFC_CREATE_SA {
        
        public ZWS_ZRFC_CREATE_SAClient() {
        }
        
        public ZWS_ZRFC_CREATE_SAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_ZRFC_CREATE_SAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZRFC_CREATE_SAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZRFC_CREATE_SAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSaResponse1 USO.Infrastructure.R3CustomerSalesAreaWebService.ZWS_ZRFC_CREATE_SA.ZrfcCreateSa(USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSaRequest request) {
            return base.Channel.ZrfcCreateSa(request);
        }
        
        public USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSaResponse ZrfcCreateSa(USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSa ZrfcCreateSa1) {
            USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSaRequest inValue = new USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSaRequest();
            inValue.ZrfcCreateSa = ZrfcCreateSa1;
            USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSaResponse1 retVal = ((USO.Infrastructure.R3CustomerSalesAreaWebService.ZWS_ZRFC_CREATE_SA)(this)).ZrfcCreateSa(inValue);
            return retVal.ZrfcCreateSaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSaResponse1> USO.Infrastructure.R3CustomerSalesAreaWebService.ZWS_ZRFC_CREATE_SA.ZrfcCreateSaAsync(USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSaRequest request) {
            return base.Channel.ZrfcCreateSaAsync(request);
        }
        
        public System.Threading.Tasks.Task<USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSaResponse1> ZrfcCreateSaAsync(USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSa ZrfcCreateSa) {
            USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSaRequest inValue = new USO.Infrastructure.R3CustomerSalesAreaWebService.ZrfcCreateSaRequest();
            inValue.ZrfcCreateSa = ZrfcCreateSa;
            return ((USO.Infrastructure.R3CustomerSalesAreaWebService.ZWS_ZRFC_CREATE_SA)(this)).ZrfcCreateSaAsync(inValue);
        }
    }
}
