//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USO.Infrastructure.R3UpdateStockLocationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="R3UpdateStockLocationService.ZWS_ZINT_SD0031")]
    public interface ZWS_ZINT_SD0031 {
        
        // CODEGEN: 操作 ZintSd0031 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_ZINT_SD0031:ZintSd0031Reques" +
            "t", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031Response1 ZintSd0031(USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_ZINT_SD0031:ZintSd0031Reques" +
            "t", ReplyAction="*")]
        System.Threading.Tasks.Task<USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031Response1> ZintSd0031Async(USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZintSd0031 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZposnrStru[] itemField;
        
        private string vbelnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZposnrStru[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Vbeln {
            get {
                return this.vbelnField;
            }
            set {
                this.vbelnField = value;
                this.RaisePropertyChanged("Vbeln");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZposnrStru : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string posnrField;
        
        private string lgortField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Posnr {
            get {
                return this.posnrField;
            }
            set {
                this.posnrField = value;
                this.RaisePropertyChanged("Posnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Lgort {
            get {
                return this.lgortField;
            }
            set {
                this.lgortField = value;
                this.RaisePropertyChanged("Lgort");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZintSd0031Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZposnrStru[] itemField;
        
        private string retcodeField;
        
        private string retmsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZposnrStru[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Retcode {
            get {
                return this.retcodeField;
            }
            set {
                this.retcodeField = value;
                this.RaisePropertyChanged("Retcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Retmsg {
            get {
                return this.retmsgField;
            }
            set {
                this.retmsgField = value;
                this.RaisePropertyChanged("Retmsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZintSd0031Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031 ZintSd0031;
        
        public ZintSd0031Request() {
        }
        
        public ZintSd0031Request(USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031 ZintSd0031) {
            this.ZintSd0031 = ZintSd0031;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZintSd0031Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031Response ZintSd0031Response;
        
        public ZintSd0031Response1() {
        }
        
        public ZintSd0031Response1(USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031Response ZintSd0031Response) {
            this.ZintSd0031Response = ZintSd0031Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_ZINT_SD0031Channel : USO.Infrastructure.R3UpdateStockLocationService.ZWS_ZINT_SD0031, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_ZINT_SD0031Client : System.ServiceModel.ClientBase<USO.Infrastructure.R3UpdateStockLocationService.ZWS_ZINT_SD0031>, USO.Infrastructure.R3UpdateStockLocationService.ZWS_ZINT_SD0031 {
        
        public ZWS_ZINT_SD0031Client() {
        }
        
        public ZWS_ZINT_SD0031Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_ZINT_SD0031Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZINT_SD0031Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZINT_SD0031Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031Response1 USO.Infrastructure.R3UpdateStockLocationService.ZWS_ZINT_SD0031.ZintSd0031(USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031Request request) {
            return base.Channel.ZintSd0031(request);
        }
        
        public USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031Response ZintSd0031(USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031 ZintSd00311) {
            USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031Request inValue = new USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031Request();
            inValue.ZintSd0031 = ZintSd00311;
            USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031Response1 retVal = ((USO.Infrastructure.R3UpdateStockLocationService.ZWS_ZINT_SD0031)(this)).ZintSd0031(inValue);
            return retVal.ZintSd0031Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031Response1> USO.Infrastructure.R3UpdateStockLocationService.ZWS_ZINT_SD0031.ZintSd0031Async(USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031Request request) {
            return base.Channel.ZintSd0031Async(request);
        }
        
        public System.Threading.Tasks.Task<USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031Response1> ZintSd0031Async(USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031 ZintSd0031) {
            USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031Request inValue = new USO.Infrastructure.R3UpdateStockLocationService.ZintSd0031Request();
            inValue.ZintSd0031 = ZintSd0031;
            return ((USO.Infrastructure.R3UpdateStockLocationService.ZWS_ZINT_SD0031)(this)).ZintSd0031Async(inValue);
        }
    }
}
