//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USO.Infrastructure.R3PaymentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="R3PaymentService.ZWS_ZINT_FI0002")]
    public interface ZWS_ZINT_FI0002 {
        
        // CODEGEN: 操作 ZintFi0002 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_ZINT_FI0002:ZintFi0002Reques" +
            "t", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        USO.Infrastructure.R3PaymentService.ZintFi0002Response1 ZintFi0002(USO.Infrastructure.R3PaymentService.ZintFi0002Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_ZINT_FI0002:ZintFi0002Reques" +
            "t", ReplyAction="*")]
        System.Threading.Tasks.Task<USO.Infrastructure.R3PaymentService.ZintFi0002Response1> ZintFi0002Async(USO.Infrastructure.R3PaymentService.ZintFi0002Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZintFi0002 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Ziaccount[] iaccountField;
        
        private Ziaccountdebit[] iaccountdebitField;
        
        private Ziaccountlend[] iaccountlendField;
        
        private Ziskfxx[] iaccountskfField;
        
        private Zmsgresp[] zmsgrespField;
        
        private Zsmsghdr zsmsghdrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ziaccount[] Iaccount {
            get {
                return this.iaccountField;
            }
            set {
                this.iaccountField = value;
                this.RaisePropertyChanged("Iaccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ziaccountdebit[] Iaccountdebit {
            get {
                return this.iaccountdebitField;
            }
            set {
                this.iaccountdebitField = value;
                this.RaisePropertyChanged("Iaccountdebit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ziaccountlend[] Iaccountlend {
            get {
                return this.iaccountlendField;
            }
            set {
                this.iaccountlendField = value;
                this.RaisePropertyChanged("Iaccountlend");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ziskfxx[] Iaccountskf {
            get {
                return this.iaccountskfField;
            }
            set {
                this.iaccountskfField = value;
                this.RaisePropertyChanged("Iaccountskf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zmsgresp[] Zmsgresp {
            get {
                return this.zmsgrespField;
            }
            set {
                this.zmsgrespField = value;
                this.RaisePropertyChanged("Zmsgresp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public Zsmsghdr Zsmsghdr {
            get {
                return this.zsmsghdrField;
            }
            set {
                this.zsmsghdrField = value;
                this.RaisePropertyChanged("Zsmsghdr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Ziaccount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string actaccountField;
        
        private string actrecordField;
        
        private string companycodeField;
        
        private string accountdateField;
        
        private string documentdateField;
        
        private string accounttypeField;
        
        private string noteField;
        
        private string currencyField;
        
        private string accountorField;
        
        private string accountplaceField;
        
        private string reserved1Field;
        
        private string reserved2Field;
        
        private string reserved3Field;
        
        private string reserved4Field;
        
        private string reserved5Field;
        
        private string transDateField;
        
        private decimal exchRateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Actaccount {
            get {
                return this.actaccountField;
            }
            set {
                this.actaccountField = value;
                this.RaisePropertyChanged("Actaccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Actrecord {
            get {
                return this.actrecordField;
            }
            set {
                this.actrecordField = value;
                this.RaisePropertyChanged("Actrecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Companycode {
            get {
                return this.companycodeField;
            }
            set {
                this.companycodeField = value;
                this.RaisePropertyChanged("Companycode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Accountdate {
            get {
                return this.accountdateField;
            }
            set {
                this.accountdateField = value;
                this.RaisePropertyChanged("Accountdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Documentdate {
            get {
                return this.documentdateField;
            }
            set {
                this.documentdateField = value;
                this.RaisePropertyChanged("Documentdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Accounttype {
            get {
                return this.accounttypeField;
            }
            set {
                this.accounttypeField = value;
                this.RaisePropertyChanged("Accounttype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Accountor {
            get {
                return this.accountorField;
            }
            set {
                this.accountorField = value;
                this.RaisePropertyChanged("Accountor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Accountplace {
            get {
                return this.accountplaceField;
            }
            set {
                this.accountplaceField = value;
                this.RaisePropertyChanged("Accountplace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Reserved1 {
            get {
                return this.reserved1Field;
            }
            set {
                this.reserved1Field = value;
                this.RaisePropertyChanged("Reserved1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Reserved2 {
            get {
                return this.reserved2Field;
            }
            set {
                this.reserved2Field = value;
                this.RaisePropertyChanged("Reserved2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Reserved3 {
            get {
                return this.reserved3Field;
            }
            set {
                this.reserved3Field = value;
                this.RaisePropertyChanged("Reserved3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Reserved4 {
            get {
                return this.reserved4Field;
            }
            set {
                this.reserved4Field = value;
                this.RaisePropertyChanged("Reserved4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Reserved5 {
            get {
                return this.reserved5Field;
            }
            set {
                this.reserved5Field = value;
                this.RaisePropertyChanged("Reserved5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string TransDate {
            get {
                return this.transDateField;
            }
            set {
                this.transDateField = value;
                this.RaisePropertyChanged("TransDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal ExchRate {
            get {
                return this.exchRateField;
            }
            set {
                this.exchRateField = value;
                this.RaisePropertyChanged("ExchRate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zsmsghdr : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceIdField;
        
        private string senderField;
        
        private string msgTypField;
        
        private string buIdField;
        
        private string cfmObjField;
        
        private string dattField;
        
        private string msgIdField;
        
        private string msgSusr1Field;
        
        private string msgSusr2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ServiceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
                this.RaisePropertyChanged("ServiceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("Sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MsgTyp {
            get {
                return this.msgTypField;
            }
            set {
                this.msgTypField = value;
                this.RaisePropertyChanged("MsgTyp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BuId {
            get {
                return this.buIdField;
            }
            set {
                this.buIdField = value;
                this.RaisePropertyChanged("BuId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CfmObj {
            get {
                return this.cfmObjField;
            }
            set {
                this.cfmObjField = value;
                this.RaisePropertyChanged("CfmObj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Datt {
            get {
                return this.dattField;
            }
            set {
                this.dattField = value;
                this.RaisePropertyChanged("Datt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MsgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
                this.RaisePropertyChanged("MsgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MsgSusr1 {
            get {
                return this.msgSusr1Field;
            }
            set {
                this.msgSusr1Field = value;
                this.RaisePropertyChanged("MsgSusr1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MsgSusr2 {
            get {
                return this.msgSusr2Field;
            }
            set {
                this.msgSusr2Field = value;
                this.RaisePropertyChanged("MsgSusr2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zmsgresp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string guidField;
        
        private string reqguidField;
        
        private string accountitemField;
        
        private string msgdateField;
        
        private string msgtimeField;
        
        private string senderField;
        
        private string receiverField;
        
        private string btypeField;
        
        private string bdocnumField;
        
        private string retidField;
        
        private string retmsgField;
        
        private string hresv1Field;
        
        private string hresv2Field;
        
        private string hresv3Field;
        
        private string hresv4Field;
        
        private string hresv5Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("Guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Reqguid {
            get {
                return this.reqguidField;
            }
            set {
                this.reqguidField = value;
                this.RaisePropertyChanged("Reqguid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Accountitem {
            get {
                return this.accountitemField;
            }
            set {
                this.accountitemField = value;
                this.RaisePropertyChanged("Accountitem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Msgdate {
            get {
                return this.msgdateField;
            }
            set {
                this.msgdateField = value;
                this.RaisePropertyChanged("Msgdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Msgtime {
            get {
                return this.msgtimeField;
            }
            set {
                this.msgtimeField = value;
                this.RaisePropertyChanged("Msgtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("Sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
                this.RaisePropertyChanged("Receiver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Btype {
            get {
                return this.btypeField;
            }
            set {
                this.btypeField = value;
                this.RaisePropertyChanged("Btype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Bdocnum {
            get {
                return this.bdocnumField;
            }
            set {
                this.bdocnumField = value;
                this.RaisePropertyChanged("Bdocnum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Retid {
            get {
                return this.retidField;
            }
            set {
                this.retidField = value;
                this.RaisePropertyChanged("Retid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Retmsg {
            get {
                return this.retmsgField;
            }
            set {
                this.retmsgField = value;
                this.RaisePropertyChanged("Retmsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Hresv1 {
            get {
                return this.hresv1Field;
            }
            set {
                this.hresv1Field = value;
                this.RaisePropertyChanged("Hresv1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Hresv2 {
            get {
                return this.hresv2Field;
            }
            set {
                this.hresv2Field = value;
                this.RaisePropertyChanged("Hresv2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Hresv3 {
            get {
                return this.hresv3Field;
            }
            set {
                this.hresv3Field = value;
                this.RaisePropertyChanged("Hresv3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Hresv4 {
            get {
                return this.hresv4Field;
            }
            set {
                this.hresv4Field = value;
                this.RaisePropertyChanged("Hresv4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Hresv5 {
            get {
                return this.hresv5Field;
            }
            set {
                this.hresv5Field = value;
                this.RaisePropertyChanged("Hresv5");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Ziskfxx : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string actaccountField;
        
        private string bukrsField;
        
        private string belnrField;
        
        private string gjahrField;
        
        private string buzeiField;
        
        private string ztypRcvField;
        
        private string zskflField;
        
        private string zrcverField;
        
        private string zrcvertField;
        
        private string banksField;
        
        private string landxField;
        
        private string banklField;
        
        private string zbankstField;
        
        private string bankaField;
        
        private string zprvcField;
        
        private string provzField;
        
        private string zrcityField;
        
        private string zrbanksField;
        
        private string zracctField;
        
        private string zflgPayField;
        
        private string zfkflField;
        
        private string zctypField;
        
        private string zctyptField;
        
        private decimal dmbtrField;
        
        private string sgtxtField;
        
        private string zusecnField;
        
        private string zareaField;
        
        private string zzjjhhField;
        
        private string zzjlbField;
        
        private string zywdyField;
        
        private string zstat2Field;
        
        private string zsmsmoblieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Actaccount {
            get {
                return this.actaccountField;
            }
            set {
                this.actaccountField = value;
                this.RaisePropertyChanged("Actaccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Bukrs {
            get {
                return this.bukrsField;
            }
            set {
                this.bukrsField = value;
                this.RaisePropertyChanged("Bukrs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Belnr {
            get {
                return this.belnrField;
            }
            set {
                this.belnrField = value;
                this.RaisePropertyChanged("Belnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Gjahr {
            get {
                return this.gjahrField;
            }
            set {
                this.gjahrField = value;
                this.RaisePropertyChanged("Gjahr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Buzei {
            get {
                return this.buzeiField;
            }
            set {
                this.buzeiField = value;
                this.RaisePropertyChanged("Buzei");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZtypRcv {
            get {
                return this.ztypRcvField;
            }
            set {
                this.ztypRcvField = value;
                this.RaisePropertyChanged("ZtypRcv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Zskfl {
            get {
                return this.zskflField;
            }
            set {
                this.zskflField = value;
                this.RaisePropertyChanged("Zskfl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Zrcver {
            get {
                return this.zrcverField;
            }
            set {
                this.zrcverField = value;
                this.RaisePropertyChanged("Zrcver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Zrcvert {
            get {
                return this.zrcvertField;
            }
            set {
                this.zrcvertField = value;
                this.RaisePropertyChanged("Zrcvert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Banks {
            get {
                return this.banksField;
            }
            set {
                this.banksField = value;
                this.RaisePropertyChanged("Banks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Landx {
            get {
                return this.landxField;
            }
            set {
                this.landxField = value;
                this.RaisePropertyChanged("Landx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Bankl {
            get {
                return this.banklField;
            }
            set {
                this.banklField = value;
                this.RaisePropertyChanged("Bankl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Zbankst {
            get {
                return this.zbankstField;
            }
            set {
                this.zbankstField = value;
                this.RaisePropertyChanged("Zbankst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Banka {
            get {
                return this.bankaField;
            }
            set {
                this.bankaField = value;
                this.RaisePropertyChanged("Banka");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Zprvc {
            get {
                return this.zprvcField;
            }
            set {
                this.zprvcField = value;
                this.RaisePropertyChanged("Zprvc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Provz {
            get {
                return this.provzField;
            }
            set {
                this.provzField = value;
                this.RaisePropertyChanged("Provz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Zrcity {
            get {
                return this.zrcityField;
            }
            set {
                this.zrcityField = value;
                this.RaisePropertyChanged("Zrcity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Zrbanks {
            get {
                return this.zrbanksField;
            }
            set {
                this.zrbanksField = value;
                this.RaisePropertyChanged("Zrbanks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Zracct {
            get {
                return this.zracctField;
            }
            set {
                this.zracctField = value;
                this.RaisePropertyChanged("Zracct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string ZflgPay {
            get {
                return this.zflgPayField;
            }
            set {
                this.zflgPayField = value;
                this.RaisePropertyChanged("ZflgPay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string Zfkfl {
            get {
                return this.zfkflField;
            }
            set {
                this.zfkflField = value;
                this.RaisePropertyChanged("Zfkfl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string Zctyp {
            get {
                return this.zctypField;
            }
            set {
                this.zctypField = value;
                this.RaisePropertyChanged("Zctyp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string Zctypt {
            get {
                return this.zctyptField;
            }
            set {
                this.zctyptField = value;
                this.RaisePropertyChanged("Zctypt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public decimal Dmbtr {
            get {
                return this.dmbtrField;
            }
            set {
                this.dmbtrField = value;
                this.RaisePropertyChanged("Dmbtr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string Sgtxt {
            get {
                return this.sgtxtField;
            }
            set {
                this.sgtxtField = value;
                this.RaisePropertyChanged("Sgtxt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string Zusecn {
            get {
                return this.zusecnField;
            }
            set {
                this.zusecnField = value;
                this.RaisePropertyChanged("Zusecn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string Zarea {
            get {
                return this.zareaField;
            }
            set {
                this.zareaField = value;
                this.RaisePropertyChanged("Zarea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string Zzjjhh {
            get {
                return this.zzjjhhField;
            }
            set {
                this.zzjjhhField = value;
                this.RaisePropertyChanged("Zzjjhh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string Zzjlb {
            get {
                return this.zzjlbField;
            }
            set {
                this.zzjlbField = value;
                this.RaisePropertyChanged("Zzjlb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string Zywdy {
            get {
                return this.zywdyField;
            }
            set {
                this.zywdyField = value;
                this.RaisePropertyChanged("Zywdy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string Zstat2 {
            get {
                return this.zstat2Field;
            }
            set {
                this.zstat2Field = value;
                this.RaisePropertyChanged("Zstat2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string Zsmsmoblie {
            get {
                return this.zsmsmoblieField;
            }
            set {
                this.zsmsmoblieField = value;
                this.RaisePropertyChanged("Zsmsmoblie");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Ziaccountlend : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string actaccountField;
        
        private string accountitemField;
        
        private string erpcostcenterField;
        
        private string erpprctrField;
        
        private string erprangeField;
        
        private string debitfirstField;
        
        private string debitcodeField;
        
        private string specialcodeField;
        
        private string creditorField;
        
        private decimal moneyField;
        
        private decimal netmoneyField;
        
        private decimal stdmoneyField;
        
        private string taxcodeField;
        
        private string assigncodeField;
        
        private string noteField;
        
        private string vbundField;
        
        private string deadlineField;
        
        private string cashcodeField;
        
        private string erpprojectField;
        
        private string idxspField;
        
        private string innerorderField;
        
        private string assetNoField;
        
        private string subNumberField;
        
        private string csTransTField;
        
        private string xref1Field;
        
        private string xref2Field;
        
        private string xref3Field;
        
        private string xnegpField;
        
        private string anredField;
        
        private string nameField;
        
        private string streetField;
        
        private string cityField;
        
        private string trPartBaField;
        
        private string materialField;
        
        private string payarticleField;
        
        private string debitrangeField;
        
        private string lendmaberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Actaccount {
            get {
                return this.actaccountField;
            }
            set {
                this.actaccountField = value;
                this.RaisePropertyChanged("Actaccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Accountitem {
            get {
                return this.accountitemField;
            }
            set {
                this.accountitemField = value;
                this.RaisePropertyChanged("Accountitem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Erpcostcenter {
            get {
                return this.erpcostcenterField;
            }
            set {
                this.erpcostcenterField = value;
                this.RaisePropertyChanged("Erpcostcenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Erpprctr {
            get {
                return this.erpprctrField;
            }
            set {
                this.erpprctrField = value;
                this.RaisePropertyChanged("Erpprctr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Erprange {
            get {
                return this.erprangeField;
            }
            set {
                this.erprangeField = value;
                this.RaisePropertyChanged("Erprange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Debitfirst {
            get {
                return this.debitfirstField;
            }
            set {
                this.debitfirstField = value;
                this.RaisePropertyChanged("Debitfirst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Debitcode {
            get {
                return this.debitcodeField;
            }
            set {
                this.debitcodeField = value;
                this.RaisePropertyChanged("Debitcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Specialcode {
            get {
                return this.specialcodeField;
            }
            set {
                this.specialcodeField = value;
                this.RaisePropertyChanged("Specialcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Creditor {
            get {
                return this.creditorField;
            }
            set {
                this.creditorField = value;
                this.RaisePropertyChanged("Creditor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal Money {
            get {
                return this.moneyField;
            }
            set {
                this.moneyField = value;
                this.RaisePropertyChanged("Money");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal Netmoney {
            get {
                return this.netmoneyField;
            }
            set {
                this.netmoneyField = value;
                this.RaisePropertyChanged("Netmoney");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal Stdmoney {
            get {
                return this.stdmoneyField;
            }
            set {
                this.stdmoneyField = value;
                this.RaisePropertyChanged("Stdmoney");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Taxcode {
            get {
                return this.taxcodeField;
            }
            set {
                this.taxcodeField = value;
                this.RaisePropertyChanged("Taxcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Assigncode {
            get {
                return this.assigncodeField;
            }
            set {
                this.assigncodeField = value;
                this.RaisePropertyChanged("Assigncode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Vbund {
            get {
                return this.vbundField;
            }
            set {
                this.vbundField = value;
                this.RaisePropertyChanged("Vbund");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Deadline {
            get {
                return this.deadlineField;
            }
            set {
                this.deadlineField = value;
                this.RaisePropertyChanged("Deadline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Cashcode {
            get {
                return this.cashcodeField;
            }
            set {
                this.cashcodeField = value;
                this.RaisePropertyChanged("Cashcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Erpproject {
            get {
                return this.erpprojectField;
            }
            set {
                this.erpprojectField = value;
                this.RaisePropertyChanged("Erpproject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Idxsp {
            get {
                return this.idxspField;
            }
            set {
                this.idxspField = value;
                this.RaisePropertyChanged("Idxsp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string Innerorder {
            get {
                return this.innerorderField;
            }
            set {
                this.innerorderField = value;
                this.RaisePropertyChanged("Innerorder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string AssetNo {
            get {
                return this.assetNoField;
            }
            set {
                this.assetNoField = value;
                this.RaisePropertyChanged("AssetNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string SubNumber {
            get {
                return this.subNumberField;
            }
            set {
                this.subNumberField = value;
                this.RaisePropertyChanged("SubNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string CsTransT {
            get {
                return this.csTransTField;
            }
            set {
                this.csTransTField = value;
                this.RaisePropertyChanged("CsTransT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string Xref1 {
            get {
                return this.xref1Field;
            }
            set {
                this.xref1Field = value;
                this.RaisePropertyChanged("Xref1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string Xref2 {
            get {
                return this.xref2Field;
            }
            set {
                this.xref2Field = value;
                this.RaisePropertyChanged("Xref2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string Xref3 {
            get {
                return this.xref3Field;
            }
            set {
                this.xref3Field = value;
                this.RaisePropertyChanged("Xref3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string Xnegp {
            get {
                return this.xnegpField;
            }
            set {
                this.xnegpField = value;
                this.RaisePropertyChanged("Xnegp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string Anred {
            get {
                return this.anredField;
            }
            set {
                this.anredField = value;
                this.RaisePropertyChanged("Anred");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string TrPartBa {
            get {
                return this.trPartBaField;
            }
            set {
                this.trPartBaField = value;
                this.RaisePropertyChanged("TrPartBa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string Material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("Material");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string Payarticle {
            get {
                return this.payarticleField;
            }
            set {
                this.payarticleField = value;
                this.RaisePropertyChanged("Payarticle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string Debitrange {
            get {
                return this.debitrangeField;
            }
            set {
                this.debitrangeField = value;
                this.RaisePropertyChanged("Debitrange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string Lendmaber {
            get {
                return this.lendmaberField;
            }
            set {
                this.lendmaberField = value;
                this.RaisePropertyChanged("Lendmaber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Ziaccountdebit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string actaccountField;
        
        private string accountitemField;
        
        private string erpcostcenterField;
        
        private string erpprctrField;
        
        private string erprangeField;
        
        private string debitfirstField;
        
        private string debitcodeField;
        
        private string specialcodeField;
        
        private string creditorField;
        
        private decimal moneyField;
        
        private decimal netmoneyField;
        
        private decimal stdmoneyField;
        
        private string taxcodeField;
        
        private string assigncodeField;
        
        private string noteField;
        
        private string vbundField;
        
        private string deadlineField;
        
        private string cashcodeField;
        
        private string erpprojectField;
        
        private string idxspField;
        
        private string innerorderField;
        
        private string assetNoField;
        
        private string subNumberField;
        
        private string csTransTField;
        
        private string xref1Field;
        
        private string xref2Field;
        
        private string xref3Field;
        
        private string xnegpField;
        
        private string anredField;
        
        private string nameField;
        
        private string streetField;
        
        private string cityField;
        
        private string trPartBaField;
        
        private string materialField;
        
        private string payarticleField;
        
        private string debitrangeField;
        
        private string debitmaberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Actaccount {
            get {
                return this.actaccountField;
            }
            set {
                this.actaccountField = value;
                this.RaisePropertyChanged("Actaccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Accountitem {
            get {
                return this.accountitemField;
            }
            set {
                this.accountitemField = value;
                this.RaisePropertyChanged("Accountitem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Erpcostcenter {
            get {
                return this.erpcostcenterField;
            }
            set {
                this.erpcostcenterField = value;
                this.RaisePropertyChanged("Erpcostcenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Erpprctr {
            get {
                return this.erpprctrField;
            }
            set {
                this.erpprctrField = value;
                this.RaisePropertyChanged("Erpprctr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Erprange {
            get {
                return this.erprangeField;
            }
            set {
                this.erprangeField = value;
                this.RaisePropertyChanged("Erprange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Debitfirst {
            get {
                return this.debitfirstField;
            }
            set {
                this.debitfirstField = value;
                this.RaisePropertyChanged("Debitfirst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Debitcode {
            get {
                return this.debitcodeField;
            }
            set {
                this.debitcodeField = value;
                this.RaisePropertyChanged("Debitcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Specialcode {
            get {
                return this.specialcodeField;
            }
            set {
                this.specialcodeField = value;
                this.RaisePropertyChanged("Specialcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Creditor {
            get {
                return this.creditorField;
            }
            set {
                this.creditorField = value;
                this.RaisePropertyChanged("Creditor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal Money {
            get {
                return this.moneyField;
            }
            set {
                this.moneyField = value;
                this.RaisePropertyChanged("Money");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal Netmoney {
            get {
                return this.netmoneyField;
            }
            set {
                this.netmoneyField = value;
                this.RaisePropertyChanged("Netmoney");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal Stdmoney {
            get {
                return this.stdmoneyField;
            }
            set {
                this.stdmoneyField = value;
                this.RaisePropertyChanged("Stdmoney");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Taxcode {
            get {
                return this.taxcodeField;
            }
            set {
                this.taxcodeField = value;
                this.RaisePropertyChanged("Taxcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Assigncode {
            get {
                return this.assigncodeField;
            }
            set {
                this.assigncodeField = value;
                this.RaisePropertyChanged("Assigncode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Vbund {
            get {
                return this.vbundField;
            }
            set {
                this.vbundField = value;
                this.RaisePropertyChanged("Vbund");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Deadline {
            get {
                return this.deadlineField;
            }
            set {
                this.deadlineField = value;
                this.RaisePropertyChanged("Deadline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Cashcode {
            get {
                return this.cashcodeField;
            }
            set {
                this.cashcodeField = value;
                this.RaisePropertyChanged("Cashcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Erpproject {
            get {
                return this.erpprojectField;
            }
            set {
                this.erpprojectField = value;
                this.RaisePropertyChanged("Erpproject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Idxsp {
            get {
                return this.idxspField;
            }
            set {
                this.idxspField = value;
                this.RaisePropertyChanged("Idxsp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string Innerorder {
            get {
                return this.innerorderField;
            }
            set {
                this.innerorderField = value;
                this.RaisePropertyChanged("Innerorder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string AssetNo {
            get {
                return this.assetNoField;
            }
            set {
                this.assetNoField = value;
                this.RaisePropertyChanged("AssetNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string SubNumber {
            get {
                return this.subNumberField;
            }
            set {
                this.subNumberField = value;
                this.RaisePropertyChanged("SubNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string CsTransT {
            get {
                return this.csTransTField;
            }
            set {
                this.csTransTField = value;
                this.RaisePropertyChanged("CsTransT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string Xref1 {
            get {
                return this.xref1Field;
            }
            set {
                this.xref1Field = value;
                this.RaisePropertyChanged("Xref1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string Xref2 {
            get {
                return this.xref2Field;
            }
            set {
                this.xref2Field = value;
                this.RaisePropertyChanged("Xref2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string Xref3 {
            get {
                return this.xref3Field;
            }
            set {
                this.xref3Field = value;
                this.RaisePropertyChanged("Xref3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string Xnegp {
            get {
                return this.xnegpField;
            }
            set {
                this.xnegpField = value;
                this.RaisePropertyChanged("Xnegp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string Anred {
            get {
                return this.anredField;
            }
            set {
                this.anredField = value;
                this.RaisePropertyChanged("Anred");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string TrPartBa {
            get {
                return this.trPartBaField;
            }
            set {
                this.trPartBaField = value;
                this.RaisePropertyChanged("TrPartBa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string Material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("Material");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string Payarticle {
            get {
                return this.payarticleField;
            }
            set {
                this.payarticleField = value;
                this.RaisePropertyChanged("Payarticle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string Debitrange {
            get {
                return this.debitrangeField;
            }
            set {
                this.debitrangeField = value;
                this.RaisePropertyChanged("Debitrange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string Debitmaber {
            get {
                return this.debitmaberField;
            }
            set {
                this.debitmaberField = value;
                this.RaisePropertyChanged("Debitmaber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZintFi0002Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Ziaccount[] iaccountField;
        
        private Ziaccountdebit[] iaccountdebitField;
        
        private Ziaccountlend[] iaccountlendField;
        
        private Ziskfxx[] iaccountskfField;
        
        private string retcodeField;
        
        private string retmsgField;
        
        private Zmsgresp[] zmsgrespField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ziaccount[] Iaccount {
            get {
                return this.iaccountField;
            }
            set {
                this.iaccountField = value;
                this.RaisePropertyChanged("Iaccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ziaccountdebit[] Iaccountdebit {
            get {
                return this.iaccountdebitField;
            }
            set {
                this.iaccountdebitField = value;
                this.RaisePropertyChanged("Iaccountdebit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ziaccountlend[] Iaccountlend {
            get {
                return this.iaccountlendField;
            }
            set {
                this.iaccountlendField = value;
                this.RaisePropertyChanged("Iaccountlend");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ziskfxx[] Iaccountskf {
            get {
                return this.iaccountskfField;
            }
            set {
                this.iaccountskfField = value;
                this.RaisePropertyChanged("Iaccountskf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Retcode {
            get {
                return this.retcodeField;
            }
            set {
                this.retcodeField = value;
                this.RaisePropertyChanged("Retcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Retmsg {
            get {
                return this.retmsgField;
            }
            set {
                this.retmsgField = value;
                this.RaisePropertyChanged("Retmsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zmsgresp[] Zmsgresp {
            get {
                return this.zmsgrespField;
            }
            set {
                this.zmsgrespField = value;
                this.RaisePropertyChanged("Zmsgresp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZintFi0002Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public USO.Infrastructure.R3PaymentService.ZintFi0002 ZintFi0002;
        
        public ZintFi0002Request() {
        }
        
        public ZintFi0002Request(USO.Infrastructure.R3PaymentService.ZintFi0002 ZintFi0002) {
            this.ZintFi0002 = ZintFi0002;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZintFi0002Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public USO.Infrastructure.R3PaymentService.ZintFi0002Response ZintFi0002Response;
        
        public ZintFi0002Response1() {
        }
        
        public ZintFi0002Response1(USO.Infrastructure.R3PaymentService.ZintFi0002Response ZintFi0002Response) {
            this.ZintFi0002Response = ZintFi0002Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_ZINT_FI0002Channel : USO.Infrastructure.R3PaymentService.ZWS_ZINT_FI0002, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_ZINT_FI0002Client : System.ServiceModel.ClientBase<USO.Infrastructure.R3PaymentService.ZWS_ZINT_FI0002>, USO.Infrastructure.R3PaymentService.ZWS_ZINT_FI0002 {
        
        public ZWS_ZINT_FI0002Client() {
        }
        
        public ZWS_ZINT_FI0002Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_ZINT_FI0002Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZINT_FI0002Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZINT_FI0002Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        USO.Infrastructure.R3PaymentService.ZintFi0002Response1 USO.Infrastructure.R3PaymentService.ZWS_ZINT_FI0002.ZintFi0002(USO.Infrastructure.R3PaymentService.ZintFi0002Request request) {
            return base.Channel.ZintFi0002(request);
        }
        
        public USO.Infrastructure.R3PaymentService.ZintFi0002Response ZintFi0002(USO.Infrastructure.R3PaymentService.ZintFi0002 ZintFi00021) {
            USO.Infrastructure.R3PaymentService.ZintFi0002Request inValue = new USO.Infrastructure.R3PaymentService.ZintFi0002Request();
            inValue.ZintFi0002 = ZintFi00021;
            USO.Infrastructure.R3PaymentService.ZintFi0002Response1 retVal = ((USO.Infrastructure.R3PaymentService.ZWS_ZINT_FI0002)(this)).ZintFi0002(inValue);
            return retVal.ZintFi0002Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<USO.Infrastructure.R3PaymentService.ZintFi0002Response1> USO.Infrastructure.R3PaymentService.ZWS_ZINT_FI0002.ZintFi0002Async(USO.Infrastructure.R3PaymentService.ZintFi0002Request request) {
            return base.Channel.ZintFi0002Async(request);
        }
        
        public System.Threading.Tasks.Task<USO.Infrastructure.R3PaymentService.ZintFi0002Response1> ZintFi0002Async(USO.Infrastructure.R3PaymentService.ZintFi0002 ZintFi0002) {
            USO.Infrastructure.R3PaymentService.ZintFi0002Request inValue = new USO.Infrastructure.R3PaymentService.ZintFi0002Request();
            inValue.ZintFi0002 = ZintFi0002;
            return ((USO.Infrastructure.R3PaymentService.ZWS_ZINT_FI0002)(this)).ZintFi0002Async(inValue);
        }
    }
}
