//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USO.Infrastructure.DeleteR3OrderItemWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="DeleteR3OrderItemWebService.ZWS_ZINT_SD0032")]
    public interface ZWS_ZINT_SD0032 {
        
        // CODEGEN: 操作 ZintSd0032 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_ZINT_SD0032:ZintSd0032Reques" +
            "t", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032Response1 ZintSd0032(USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_ZINT_SD0032:ZintSd0032Reques" +
            "t", ReplyAction="*")]
        System.Threading.Tasks.Task<USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032Response1> ZintSd0032Async(USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZintSd0032 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EdmasnPosnrTs[] posnrField;
        
        private string vbelnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EdmasnPosnrTs[] Posnr {
            get {
                return this.posnrField;
            }
            set {
                this.posnrField = value;
                this.RaisePropertyChanged("Posnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Vbeln {
            get {
                return this.vbelnField;
            }
            set {
                this.vbelnField = value;
                this.RaisePropertyChanged("Vbeln");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class EdmasnPosnrTs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string posnrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Posnr {
            get {
                return this.posnrField;
            }
            set {
                this.posnrField = value;
                this.RaisePropertyChanged("Posnr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZintSd0032Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EdmasnPosnrTs[] posnrField;
        
        private string retcodeField;
        
        private string retmsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EdmasnPosnrTs[] Posnr {
            get {
                return this.posnrField;
            }
            set {
                this.posnrField = value;
                this.RaisePropertyChanged("Posnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Retcode {
            get {
                return this.retcodeField;
            }
            set {
                this.retcodeField = value;
                this.RaisePropertyChanged("Retcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Retmsg {
            get {
                return this.retmsgField;
            }
            set {
                this.retmsgField = value;
                this.RaisePropertyChanged("Retmsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZintSd0032Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032 ZintSd0032;
        
        public ZintSd0032Request() {
        }
        
        public ZintSd0032Request(USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032 ZintSd0032) {
            this.ZintSd0032 = ZintSd0032;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZintSd0032Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032Response ZintSd0032Response;
        
        public ZintSd0032Response1() {
        }
        
        public ZintSd0032Response1(USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032Response ZintSd0032Response) {
            this.ZintSd0032Response = ZintSd0032Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_ZINT_SD0032Channel : USO.Infrastructure.DeleteR3OrderItemWebService.ZWS_ZINT_SD0032, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_ZINT_SD0032Client : System.ServiceModel.ClientBase<USO.Infrastructure.DeleteR3OrderItemWebService.ZWS_ZINT_SD0032>, USO.Infrastructure.DeleteR3OrderItemWebService.ZWS_ZINT_SD0032 {
        
        public ZWS_ZINT_SD0032Client() {
        }
        
        public ZWS_ZINT_SD0032Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_ZINT_SD0032Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZINT_SD0032Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZINT_SD0032Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032Response1 USO.Infrastructure.DeleteR3OrderItemWebService.ZWS_ZINT_SD0032.ZintSd0032(USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032Request request) {
            return base.Channel.ZintSd0032(request);
        }
        
        public USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032Response ZintSd0032(USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032 ZintSd00321) {
            USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032Request inValue = new USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032Request();
            inValue.ZintSd0032 = ZintSd00321;
            USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032Response1 retVal = ((USO.Infrastructure.DeleteR3OrderItemWebService.ZWS_ZINT_SD0032)(this)).ZintSd0032(inValue);
            return retVal.ZintSd0032Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032Response1> USO.Infrastructure.DeleteR3OrderItemWebService.ZWS_ZINT_SD0032.ZintSd0032Async(USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032Request request) {
            return base.Channel.ZintSd0032Async(request);
        }
        
        public System.Threading.Tasks.Task<USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032Response1> ZintSd0032Async(USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032 ZintSd0032) {
            USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032Request inValue = new USO.Infrastructure.DeleteR3OrderItemWebService.ZintSd0032Request();
            inValue.ZintSd0032 = ZintSd0032;
            return ((USO.Infrastructure.DeleteR3OrderItemWebService.ZWS_ZINT_SD0032)(this)).ZintSd0032Async(inValue);
        }
    }
}
