//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USO.Infrastructure.R3OrderWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="R3OrderWebService.ZWS_ZINT_SD0001")]
    public interface ZWS_ZINT_SD0001 {
        
        // CODEGEN: 操作 ZintSd0001 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_ZINT_SD0001:ZintSd0001Reques" +
            "t", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        USO.Infrastructure.R3OrderWebService.ZintSd0001Response1 ZintSd0001(USO.Infrastructure.R3OrderWebService.ZintSd0001Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_ZINT_SD0001:ZintSd0001Reques" +
            "t", ReplyAction="*")]
        System.Threading.Tasks.Task<USO.Infrastructure.R3OrderWebService.ZintSd0001Response1> ZintSd0001Async(USO.Infrastructure.R3OrderWebService.ZintSd0001Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZintSd0001 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Zsconditions[] zsconditionsField;
        
        private Zsflbh[] zsflbhField;
        
        private Zsmsghdr zsmsghdrField;
        
        private Zssohdr zssohdrField;
        
        private Zssoitem[] zssoitemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zsconditions[] Zsconditions {
            get {
                return this.zsconditionsField;
            }
            set {
                this.zsconditionsField = value;
                this.RaisePropertyChanged("Zsconditions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zsflbh[] Zsflbh {
            get {
                return this.zsflbhField;
            }
            set {
                this.zsflbhField = value;
                this.RaisePropertyChanged("Zsflbh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Zsmsghdr Zsmsghdr {
            get {
                return this.zsmsghdrField;
            }
            set {
                this.zsmsghdrField = value;
                this.RaisePropertyChanged("Zsmsghdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Zssohdr Zssohdr {
            get {
                return this.zssohdrField;
            }
            set {
                this.zssohdrField = value;
                this.RaisePropertyChanged("Zssohdr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zssoitem[] Zssoitem {
            get {
                return this.zssoitemField;
            }
            set {
                this.zssoitemField = value;
                this.RaisePropertyChanged("Zssoitem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zsconditions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string posnrField;
        
        private string kschlField;
        
        private decimal kbetrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Posnr {
            get {
                return this.posnrField;
            }
            set {
                this.posnrField = value;
                this.RaisePropertyChanged("Posnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Kschl {
            get {
                return this.kschlField;
            }
            set {
                this.kschlField = value;
                this.RaisePropertyChanged("Kschl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Kbetr {
            get {
                return this.kbetrField;
            }
            set {
                this.kbetrField = value;
                this.RaisePropertyChanged("Kbetr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zsmsgresp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string guidField;
        
        private string reqguidField;
        
        private string dattField;
        
        private string senderField;
        
        private string receiverField;
        
        private string msgTypField;
        
        private string objSapField;
        
        private string objOthField;
        
        private string retidField;
        
        private string retmsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("Guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Reqguid {
            get {
                return this.reqguidField;
            }
            set {
                this.reqguidField = value;
                this.RaisePropertyChanged("Reqguid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Datt {
            get {
                return this.dattField;
            }
            set {
                this.dattField = value;
                this.RaisePropertyChanged("Datt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("Sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
                this.RaisePropertyChanged("Receiver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MsgTyp {
            get {
                return this.msgTypField;
            }
            set {
                this.msgTypField = value;
                this.RaisePropertyChanged("MsgTyp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ObjSap {
            get {
                return this.objSapField;
            }
            set {
                this.objSapField = value;
                this.RaisePropertyChanged("ObjSap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ObjOth {
            get {
                return this.objOthField;
            }
            set {
                this.objOthField = value;
                this.RaisePropertyChanged("ObjOth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Retid {
            get {
                return this.retidField;
            }
            set {
                this.retidField = value;
                this.RaisePropertyChanged("Retid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Retmsg {
            get {
                return this.retmsgField;
            }
            set {
                this.retmsgField = value;
                this.RaisePropertyChanged("Retmsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zssoitem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string posnrField;
        
        private string matnrField;
        
        private string lgortField;
        
        private string werksField;
        
        private string chargField;
        
        private decimal kbetrField;
        
        private decimal kwmengField;
        
        private string bstkdEField;
        
        private string kdmatField;
        
        private string kdkg1Field;
        
        private string stlalField;
        
        private string mvgr3Field;
        
        private string empstField;
        
        private string abgruField;
        
        private string lifspField;
        
        private decimal zmengField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Posnr {
            get {
                return this.posnrField;
            }
            set {
                this.posnrField = value;
                this.RaisePropertyChanged("Posnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
                this.RaisePropertyChanged("Matnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Lgort {
            get {
                return this.lgortField;
            }
            set {
                this.lgortField = value;
                this.RaisePropertyChanged("Lgort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Werks {
            get {
                return this.werksField;
            }
            set {
                this.werksField = value;
                this.RaisePropertyChanged("Werks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Charg {
            get {
                return this.chargField;
            }
            set {
                this.chargField = value;
                this.RaisePropertyChanged("Charg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal Kbetr {
            get {
                return this.kbetrField;
            }
            set {
                this.kbetrField = value;
                this.RaisePropertyChanged("Kbetr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal Kwmeng {
            get {
                return this.kwmengField;
            }
            set {
                this.kwmengField = value;
                this.RaisePropertyChanged("Kwmeng");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string BstkdE {
            get {
                return this.bstkdEField;
            }
            set {
                this.bstkdEField = value;
                this.RaisePropertyChanged("BstkdE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Kdmat {
            get {
                return this.kdmatField;
            }
            set {
                this.kdmatField = value;
                this.RaisePropertyChanged("Kdmat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Kdkg1 {
            get {
                return this.kdkg1Field;
            }
            set {
                this.kdkg1Field = value;
                this.RaisePropertyChanged("Kdkg1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Stlal {
            get {
                return this.stlalField;
            }
            set {
                this.stlalField = value;
                this.RaisePropertyChanged("Stlal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Mvgr3 {
            get {
                return this.mvgr3Field;
            }
            set {
                this.mvgr3Field = value;
                this.RaisePropertyChanged("Mvgr3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Empst {
            get {
                return this.empstField;
            }
            set {
                this.empstField = value;
                this.RaisePropertyChanged("Empst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Abgru {
            get {
                return this.abgruField;
            }
            set {
                this.abgruField = value;
                this.RaisePropertyChanged("Abgru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Lifsp {
            get {
                return this.lifspField;
            }
            set {
                this.lifspField = value;
                this.RaisePropertyChanged("Lifsp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public decimal Zmeng {
            get {
                return this.zmengField;
            }
            set {
                this.zmengField = value;
                this.RaisePropertyChanged("Zmeng");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zssohdr : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string auartField;
        
        private string vkorgField;
        
        private string vtwegField;
        
        private string spartField;
        
        private string vkgrpField;
        
        private string vkburField;
        
        private string soldtoField;
        
        private string soldtoCwField;
        
        private string soldtoNameField;
        
        private string shiptoField;
        
        private string shiptoCwField;
        
        private string shiptoNameField;
        
        private string abladField;
        
        private string abrvwField;
        
        private string augruField;
        
        private string inco1Field;
        
        private string inco2Field;
        
        private string bstkdField;
        
        private string bstdkField;
        
        private string bstkdEField;
        
        private string bstzdField;
        
        private string submiField;
        
        private string ihrezField;
        
        private string bnameField;
        
        private string ernamField;
        
        private string lifskField;
        
        private string ihrezEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Auart {
            get {
                return this.auartField;
            }
            set {
                this.auartField = value;
                this.RaisePropertyChanged("Auart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Vkorg {
            get {
                return this.vkorgField;
            }
            set {
                this.vkorgField = value;
                this.RaisePropertyChanged("Vkorg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Vtweg {
            get {
                return this.vtwegField;
            }
            set {
                this.vtwegField = value;
                this.RaisePropertyChanged("Vtweg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Spart {
            get {
                return this.spartField;
            }
            set {
                this.spartField = value;
                this.RaisePropertyChanged("Spart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Vkgrp {
            get {
                return this.vkgrpField;
            }
            set {
                this.vkgrpField = value;
                this.RaisePropertyChanged("Vkgrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Vkbur {
            get {
                return this.vkburField;
            }
            set {
                this.vkburField = value;
                this.RaisePropertyChanged("Vkbur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Soldto {
            get {
                return this.soldtoField;
            }
            set {
                this.soldtoField = value;
                this.RaisePropertyChanged("Soldto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SoldtoCw {
            get {
                return this.soldtoCwField;
            }
            set {
                this.soldtoCwField = value;
                this.RaisePropertyChanged("SoldtoCw");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SoldtoName {
            get {
                return this.soldtoNameField;
            }
            set {
                this.soldtoNameField = value;
                this.RaisePropertyChanged("SoldtoName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Shipto {
            get {
                return this.shiptoField;
            }
            set {
                this.shiptoField = value;
                this.RaisePropertyChanged("Shipto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ShiptoCw {
            get {
                return this.shiptoCwField;
            }
            set {
                this.shiptoCwField = value;
                this.RaisePropertyChanged("ShiptoCw");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ShiptoName {
            get {
                return this.shiptoNameField;
            }
            set {
                this.shiptoNameField = value;
                this.RaisePropertyChanged("ShiptoName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Ablad {
            get {
                return this.abladField;
            }
            set {
                this.abladField = value;
                this.RaisePropertyChanged("Ablad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Abrvw {
            get {
                return this.abrvwField;
            }
            set {
                this.abrvwField = value;
                this.RaisePropertyChanged("Abrvw");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Augru {
            get {
                return this.augruField;
            }
            set {
                this.augruField = value;
                this.RaisePropertyChanged("Augru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Inco1 {
            get {
                return this.inco1Field;
            }
            set {
                this.inco1Field = value;
                this.RaisePropertyChanged("Inco1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Inco2 {
            get {
                return this.inco2Field;
            }
            set {
                this.inco2Field = value;
                this.RaisePropertyChanged("Inco2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Bstkd {
            get {
                return this.bstkdField;
            }
            set {
                this.bstkdField = value;
                this.RaisePropertyChanged("Bstkd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Bstdk {
            get {
                return this.bstdkField;
            }
            set {
                this.bstdkField = value;
                this.RaisePropertyChanged("Bstdk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string BstkdE {
            get {
                return this.bstkdEField;
            }
            set {
                this.bstkdEField = value;
                this.RaisePropertyChanged("BstkdE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string Bstzd {
            get {
                return this.bstzdField;
            }
            set {
                this.bstzdField = value;
                this.RaisePropertyChanged("Bstzd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string Submi {
            get {
                return this.submiField;
            }
            set {
                this.submiField = value;
                this.RaisePropertyChanged("Submi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string Ihrez {
            get {
                return this.ihrezField;
            }
            set {
                this.ihrezField = value;
                this.RaisePropertyChanged("Ihrez");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string Bname {
            get {
                return this.bnameField;
            }
            set {
                this.bnameField = value;
                this.RaisePropertyChanged("Bname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string Ernam {
            get {
                return this.ernamField;
            }
            set {
                this.ernamField = value;
                this.RaisePropertyChanged("Ernam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string Lifsk {
            get {
                return this.lifskField;
            }
            set {
                this.lifskField = value;
                this.RaisePropertyChanged("Lifsk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string IhrezE {
            get {
                return this.ihrezEField;
            }
            set {
                this.ihrezEField = value;
                this.RaisePropertyChanged("IhrezE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zsmsghdr : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceIdField;
        
        private string senderField;
        
        private string msgTypField;
        
        private string buIdField;
        
        private string cfmObjField;
        
        private string dattField;
        
        private string msgIdField;
        
        private string msgSusr1Field;
        
        private string msgSusr2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ServiceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
                this.RaisePropertyChanged("ServiceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("Sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MsgTyp {
            get {
                return this.msgTypField;
            }
            set {
                this.msgTypField = value;
                this.RaisePropertyChanged("MsgTyp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BuId {
            get {
                return this.buIdField;
            }
            set {
                this.buIdField = value;
                this.RaisePropertyChanged("BuId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CfmObj {
            get {
                return this.cfmObjField;
            }
            set {
                this.cfmObjField = value;
                this.RaisePropertyChanged("CfmObj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Datt {
            get {
                return this.dattField;
            }
            set {
                this.dattField = value;
                this.RaisePropertyChanged("Datt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MsgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
                this.RaisePropertyChanged("MsgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MsgSusr1 {
            get {
                return this.msgSusr1Field;
            }
            set {
                this.msgSusr1Field = value;
                this.RaisePropertyChanged("MsgSusr1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MsgSusr2 {
            get {
                return this.msgSusr2Field;
            }
            set {
                this.msgSusr2Field = value;
                this.RaisePropertyChanged("MsgSusr2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zsflbh : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string posnrField;
        
        private string zbhField;
        
        private decimal kbetrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Posnr {
            get {
                return this.posnrField;
            }
            set {
                this.posnrField = value;
                this.RaisePropertyChanged("Posnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Zbh {
            get {
                return this.zbhField;
            }
            set {
                this.zbhField = value;
                this.RaisePropertyChanged("Zbh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Kbetr {
            get {
                return this.kbetrField;
            }
            set {
                this.kbetrField = value;
                this.RaisePropertyChanged("Kbetr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZintSd0001Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Zsconditions[] zsconditionsField;
        
        private Zsflbh[] zsflbhField;
        
        private Zsmsgresp zsmsgrespField;
        
        private Zssoitem[] zssoitemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zsconditions[] Zsconditions {
            get {
                return this.zsconditionsField;
            }
            set {
                this.zsconditionsField = value;
                this.RaisePropertyChanged("Zsconditions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zsflbh[] Zsflbh {
            get {
                return this.zsflbhField;
            }
            set {
                this.zsflbhField = value;
                this.RaisePropertyChanged("Zsflbh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Zsmsgresp Zsmsgresp {
            get {
                return this.zsmsgrespField;
            }
            set {
                this.zsmsgrespField = value;
                this.RaisePropertyChanged("Zsmsgresp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zssoitem[] Zssoitem {
            get {
                return this.zssoitemField;
            }
            set {
                this.zssoitemField = value;
                this.RaisePropertyChanged("Zssoitem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZintSd0001Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public USO.Infrastructure.R3OrderWebService.ZintSd0001 ZintSd0001;
        
        public ZintSd0001Request() {
        }
        
        public ZintSd0001Request(USO.Infrastructure.R3OrderWebService.ZintSd0001 ZintSd0001) {
            this.ZintSd0001 = ZintSd0001;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZintSd0001Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public USO.Infrastructure.R3OrderWebService.ZintSd0001Response ZintSd0001Response;
        
        public ZintSd0001Response1() {
        }
        
        public ZintSd0001Response1(USO.Infrastructure.R3OrderWebService.ZintSd0001Response ZintSd0001Response) {
            this.ZintSd0001Response = ZintSd0001Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_ZINT_SD0001Channel : USO.Infrastructure.R3OrderWebService.ZWS_ZINT_SD0001, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_ZINT_SD0001Client : System.ServiceModel.ClientBase<USO.Infrastructure.R3OrderWebService.ZWS_ZINT_SD0001>, USO.Infrastructure.R3OrderWebService.ZWS_ZINT_SD0001 {
        
        public ZWS_ZINT_SD0001Client() {
        }
        
        public ZWS_ZINT_SD0001Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_ZINT_SD0001Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZINT_SD0001Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZINT_SD0001Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        USO.Infrastructure.R3OrderWebService.ZintSd0001Response1 USO.Infrastructure.R3OrderWebService.ZWS_ZINT_SD0001.ZintSd0001(USO.Infrastructure.R3OrderWebService.ZintSd0001Request request) {
            return base.Channel.ZintSd0001(request);
        }
        
        public USO.Infrastructure.R3OrderWebService.ZintSd0001Response ZintSd0001(USO.Infrastructure.R3OrderWebService.ZintSd0001 ZintSd00011) {
            USO.Infrastructure.R3OrderWebService.ZintSd0001Request inValue = new USO.Infrastructure.R3OrderWebService.ZintSd0001Request();
            inValue.ZintSd0001 = ZintSd00011;
            USO.Infrastructure.R3OrderWebService.ZintSd0001Response1 retVal = ((USO.Infrastructure.R3OrderWebService.ZWS_ZINT_SD0001)(this)).ZintSd0001(inValue);
            return retVal.ZintSd0001Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<USO.Infrastructure.R3OrderWebService.ZintSd0001Response1> USO.Infrastructure.R3OrderWebService.ZWS_ZINT_SD0001.ZintSd0001Async(USO.Infrastructure.R3OrderWebService.ZintSd0001Request request) {
            return base.Channel.ZintSd0001Async(request);
        }
        
        public System.Threading.Tasks.Task<USO.Infrastructure.R3OrderWebService.ZintSd0001Response1> ZintSd0001Async(USO.Infrastructure.R3OrderWebService.ZintSd0001 ZintSd0001) {
            USO.Infrastructure.R3OrderWebService.ZintSd0001Request inValue = new USO.Infrastructure.R3OrderWebService.ZintSd0001Request();
            inValue.ZintSd0001 = ZintSd0001;
            return ((USO.Infrastructure.R3OrderWebService.ZWS_ZINT_SD0001)(this)).ZintSd0001Async(inValue);
        }
    }
}
